# Generated by Django 4.1.1 on 2022-09-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_forums'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forums',
            new_name='Forum',
        ),
    ]
