# Generated by Django 4.1.1 on 2022-09-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_forum_category_forum_date_forum_number_patients_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sessions',
            new_name='Session',
        ),
    ]
