# Generated by Django 4.1.1 on 2022-09-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_doctor_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='wallet_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='wallet_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
