# Generated by Django 4.1.1 on 2022-10-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_patient_forum_sponsor_forum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='past_medication',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
