# Generated by Django 4.1.1 on 2022-10-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_patient_past_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='certificate',
            field=models.FileField(default=12, upload_to=''),
            preserve_default=False,
        ),
    ]
