# Generated by Django 4.1.1 on 2022-10-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_doctor_certificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='organization_name',
            new_name='organisation_name',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='certificate',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
