# Generated by Django 4.1.1 on 2022-10-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_rename_organization_name_sponsor_organisation_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='approved',
            new_name='is_approved',
        ),
        migrations.RenameField(
            model_name='sponsor',
            old_name='approved',
            new_name='is_approved',
        ),
    ]
