# Generated by Django 4.1.1 on 2022-10-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_rename_approved_doctor_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='is_approved',
            field=models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('B', 'Banned')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='is_approved',
            field=models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('B', 'Banned')], default='P', max_length=10),
        ),
    ]
